CC = g++

#TODO: Add -Wall
CXXFLAGS = -g -std=c++0x -I./include -I../include

OUTPUT = trie

SRC = source/mstring.cpp\
        source/trie.cpp\
        main.cpp

OBJS = ${SRC:.cpp=.o}

trie : ${OBJS} include/mstring.h include/mvector.h include/trie.h include/logger.h
	${CC} ${CXXFLAGS} -o ${OUTPUT} ${OBJS}

clean :
	@rm ./source/*.o